version: '3.7'
services:

  traefik:
    image: traefik:1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - 8000:80
      - 8080:8080
    networks:
      - main
    restart: unless-stopped
    command: ["traefik", "--accesslog", "--api", "--docker", "--docker.exposedbydefault=false"]

  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    labels:
      - traefik.backend=back
      - traefik.docker.network=main
      - traefik.enable=true
      - traefik.port=8000
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - traefik
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    volumes:
      - ./data/mongodb:/data/db
      - ./scripts/mongodb-init-db.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 27017:27017
    networks:
      - main
    env_file:
      - .env
    restart: unless-stopped

networks:
  main:
